# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
data:
  GOOGLE_API_KEY: "<API_KEY_HERE"
  GOOGLE_GENAI_USE_VERTEXAI: "False"
  AIR_AGENT_URL: "http://airbnb-agent-service:10002"
  WEA_AGENT_URL: "http://weather-agent-service:10001"
